config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="News Crawler API",
      default_version='v1',
      description="This project provide API endpoints for Nes Crawling",
      #terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="omolojakazeem@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    #path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico')))

]

news/urls.py
from django.urls import path
from rest_framework import routers

from .apis import NewsList, NewsRetrieveUpdateDelete
from .views import NewsHomeView, JobsHomeView, StoryHomeView, PollHomeView, ItemDetailView

app_name = 'news'

apipatterns = [
    path('api/', NewsList.as_view(), name='news'),
    path('api/detail/<int:id>', NewsRetrieveUpdateDelete.as_view(), name='news_detail'),
]

urlpatterns = [
    path('', NewsHomeView.as_view(), name='news_home'),
    path('jobs/', JobsHomeView.as_view(), name='news_job_home'),
    path('stories/', StoryHomeView.as_view(), name='news_story_home'),
    path('polls/', PollHomeView.as_view(), name='news_poll_home'),
    path('detail/<int:pk>', ItemDetailView.as_view(), name='news_item_detail'),
]+apipatterns

news/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models


NEWS_TYPE = (
    ("JOB", "JOB"),
    ("COMMENT", "COMMENT"),
    ("STORY", "STORY"),
    ("POLL", "POLL"),
    ("POLLOPT", "POLLOPT"),
)


class News(models.Model):
    """
    Model: News
    Database Table to hold News instances
    """
    s_n = models.BigIntegerField(unique=True, null=True, blank=True)
    deleted = models.BooleanField(default=False)
    type = models.CharField(max_length=7, choices=NEWS_TYPE, null=True, blank=True)
    by = models.CharField(max_length=255, null=True, blank=True)
    time = models.IntegerField(null=True, blank=True)
    dead = models.BooleanField(default=False)
    kids = ArrayField(models.IntegerField(null=True, blank=True), null=True, blank=True)
    parts = ArrayField(models.IntegerField(null=True, blank=True), null=True, blank=True)
    descendants = models.IntegerField(null=True, blank=True)
    parent = models.IntegerField(null=True, blank=True)
    score = models.IntegerField(null=True, blank=True)
    title = models.CharField(max_length=500, null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    synced = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-added']

    def __str__(self):
        if self.title:
            return f"News Item - {self.title} (Type - {self.type})"
        else:
            return f"News Item - {self.pk} (Type - {self.type})"

news/views.py
from django.core.paginator import Paginator
from django.db.models import QuerySet, Q
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import ListView, DetailView

from news.models import News


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


class NewsHomeView(ListView):
    paginate_by = 10
    model = News
    template_name = 'news/index.html'
    queryset = News.objects.all()

    def get_queryset(self):
        self.get_copy = self.request.GET.copy()
        self.search = self.get_copy.get("search", None)
        self.news_type = self.get_copy.get("type", None)

        assert self.queryset is not None, (
                "'%s' should either include a `queryset` attribute, "
                "or override the `get_queryset()` method."
                % self.__class__.__name__
        )

        queryset = self.queryset.filter(Q(type="JOB") | Q(type="STORY") | Q(type="POLL"))
        if isinstance(queryset, QuerySet):
            if self.search:
                queryset = queryset.filter(text__icontains=self.search)
            if self.news_type:
                if self.news_type == 'all':
                    queryset = queryset
                else:
                    queryset = queryset.filter(type=self.news_type.upper())
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):

        parameters = self.get_copy.pop('page', True) and self.get_copy.urlencode()
        context = super(NewsHomeView, self).get_context_data(object_list=None, **kwargs)
        context['parameters'] = parameters
        if self.search:
            context['search'] = self.search
        if self.news_type:
            context['story'] = context['job'] = context['poll'] = False
            context['all'] = True
            if self.news_type == 'job':
                context['job'] = True
                context['all'] = False
            elif self.news_type == 'story':
                context['story'] = True
                context['all'] = False
            elif self.news_type == 'poll':
                context['poll'] = True
                context['all'] = False
        return context


class JobsHomeView(ListView):
    paginate_by = 10
    model = News
    template_name = 'news/jobs.html'
    queryset = News.objects.all()

    def get_queryset(self):
        get_copy = self.request.GET.copy()
        self.search = get_copy.get("search", None)

        assert self.queryset is not None, (
                "'%s' should either include a `queryset` attribute, "
                "or override the `get_queryset()` method."
                % self.__class__.__name__
        )

        queryset = self.queryset
        if isinstance(queryset, QuerySet):
            if self.search:
                queryset = queryset.filter(type="JOB", text__icontains=self.search)
            else:
                queryset = queryset.filter(type="JOB")
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        get_copy = self.request.GET.copy()
        parameters = get_copy.pop('page', True) and get_copy.urlencode()
        context = super(JobsHomeView, self).get_context_data(object_list=None, **kwargs)
        context['parameters'] = parameters
        if self.search:
            context['search'] = self.search

        return context


class PollHomeView(ListView):
    paginate_by = 10
    model = News
    template_name = 'news/polls.html'
    queryset = News.objects.all()

    def get_queryset(self):
        get_copy = self.request.GET.copy()
        self.search = get_copy.get("search", None)

        assert self.queryset is not None, (
                "'%s' should either include a `queryset` attribute, "
                "or override the `get_queryset()` method."
                % self.__class__.__name__
        )

        queryset = self.queryset
        if isinstance(queryset, QuerySet):
            if self.search:
                queryset = queryset.filter(type="POLL", text__icontains=self.search)
            else:
                queryset = queryset.filter(type="POLL")
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        get_copy = self.request.GET.copy()
        parameters = get_copy.pop('page', True) and get_copy.urlencode()
        context = super(PollHomeView, self).get_context_data(object_list=None, **kwargs)
        context['parameters'] = parameters
        if self.search:
            context['search'] = self.search

        return context


class StoryHomeView(ListView):
    paginate_by = 10
    model = News
    template_name = 'news/story.html'
    queryset = News.objects.all()

    def get_queryset(self):
        get_copy = self.request.GET.copy()
        self.search = get_copy.get("search", None)
        assert self.queryset is not None, (
                "'%s' should either include a `queryset` attribute, "
                "or override the `get_queryset()` method."
                % self.__class__.__name__
        )

        queryset = self.queryset
        if isinstance(queryset, QuerySet):
            if self.search:
                queryset = queryset.filter(type="STORY", text__icontains=self.search)
            else:
                queryset = queryset.filter(type="STORY")
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        get_copy = self.request.GET.copy()
        parameters = get_copy.pop('page', True) and get_copy.urlencode()
        context = super(StoryHomeView, self).get_context_data(object_list=None, **kwargs)
        context['parameters'] = parameters
        if self.search:
            context['search'] = self.search

        return context


class ItemDetailView(DetailView):
    template_name = 'news/detail.html'
    model = News

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ItemDetailView, self).get_context_data(object_list=None, **kwargs)

        comments = News.objects.filter(type="COMMENT", parent=str(self.get_object().s_n))
        context['comments'] = comments

        return context

templates/news/detail.html
{% extends "layout/base.html" %}
{% load static %}
{% block title %}
    Jobs - News Crawler
{% endblock %}
{% block custom_static %}
    {% endblock %}
{% block navbar %}
{% endblock %}

{% block content %}
    <main>
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">{{object.title}}</h1>
                    <p class="lead text-muted">
                        {% if object.text %}
                            {{object.text|safe}}
                        {% endif %}
                    </p>
                    <p>
                        <a href="#" class="btn btn-primary my-2">By: {{object.by}}</a>
                          {% if object.type == 'JOB' %}
                                <a href="#" class="btn btn-secondary my-2">
                                    Type: {{object.type}}
                                </a>
                          {% elif object.type == 'STORY' %}
                                <a href="#" class="btn btn-success my-2">
                                    Type: {{object.type}}
                                </a>
                          {% elif object.type == 'POLL' %}
                                <a href="#" class="btn btn-primary my-2">
                                    Type: {{object.type}}
                                </a>
                          {% endif %}
                                <a href="#" class="btn btn-warning my-2">
                                    Score: {{object.score}}
                                </a>

                    </p>URL:
                        <a href="#">
                            {{object.url}}
                        </a>

                </div>
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">
                {% if object.type == "poll" %}
                    Poll Options
                {% else %}
                    Comments
                {% endif %}
                {% for comment in comments %}
                    <p class="pb-3 mb-0 small lh-sm">
                        <strong class="d-block text-gray-dark">Comment by: @{{comment.by}} at {{comment.added|timesince}} ago</strong>
                        <br>
                        {{comment.text|safe}}
                    </p>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/news/news.js' %}"></script>
{% endblock %}

templates/news/index.html
{% extends "layout/base.html" %}
{% load static %}
{% load timeConverter %}
{% block title %}
    Home - News Crawler
{% endblock %}
{% block custom_static %}
    {% endblock %}
{% block navbar %}
{% endblock %}

{% block content %}
    <main class="container">
        <div class="align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
            <form action="" method="get">
                <div class="row">
                    <div class="col-sm-5">
                        <input type="text" value="{{search}}" name="search" class="form-control search_bar" placeholder="search text">
                    </div>
                    <div class="col-sm-5">
                        <select class="form-select" aria-label=".form-select-sm example" name="type" id="">
                            <option value="all" {% if all %} selected {% endif %}>ALL</option>
                            <option value="job" {% if job %} selected {% endif %}>JOB</option>
                            <option value="story" {% if story %} selected {% endif %}>STORY</option>
                            <option value="poll" {% if poll %} selected {% endif %}>POLL</option>
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-primary btn-block">Search</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <h6 class="border-bottom pb-2 mb-0">
                {% block page_title %}
                    All News updates
                {% endblock %}
            </h6>
            {% for item in page_obj %}
                <div class="d-flex text-muted pt-3">
                    <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
                    <p class="pb-3 mb-0 small lh-sm">
                        <strong class="d-block text-gray-dark">Posted by: @{{item.by}} | added: {{item.time|time_converter}}</strong>
                        <a href="{% url 'news:news_item_detail' item.pk %}">
                            {{item.title}}
                        </a>
                        <br>
                        <br>
                        Synchronised {{item.added|timesince}} ago.
                    </p>
                </div>
            {% endfor %}
          <small>
              {% if is_paginated %}
                <hr>
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center pagination-sm">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{parameters}}" tabindex="-1">Previous</a>
                                </li>

                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                                </li>
                            {% endif %}
                            {% for object in page_obj.paginator.page_range %}
                                <li class="page-item"><a class="page-link " href="?page={{ forloop.counter }}&{{parameters}}">{{ forloop.counter }}</a></li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{parameters}}">Next</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="#">Next</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
              {% endif %}
          </small>
      </div>
    </main>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/news/news.js' %}"></script>
{% endblock %}

templates/news/jobs.html
{% extends "layout/base.html" %}
{% load static %}
{% load timeConverter %}
{% block title %}
    Jobs - News Crawler
{% endblock %}
{% block custom_static %}
    {% endblock %}
{% block navbar %}
{% endblock %}

{% block content %}
    <main class="container">
        <div class="align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
            <form action="" method="get">
                <div class="row">
                    <div class="col-sm-10">
                        <input type="text" value="{{search}}" name="search" class="form-control search_bar" placeholder="search text">
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-primary btn-block">Search</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <h6 class="border-bottom pb-2 mb-0">
                {% block page_title %}
                    Jobs updates
                {% endblock %}
            </h6>
            <div id="replaceable_content" data-filter-url="{% url 'news:news_job_home' %}">
                {% for item in page_obj %}
                    <div class="d-flex text-muted pt-3">
                        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>

                        <p class="pb-3 mb-0 small lh-sm border-bottom">
                            <strong class="d-block text-gray-dark">Posted by: @{{item.by}} | added: {{item.time|time_converter}}</strong>
                            <a href="{% url 'news:news_item_detail' item.pk %}">
                                {{item.title}}
                            </a>
                            <br>
                            <br>
                            Synchronised {{item.added|timesince}} ago.
                        </p>
                    </div>
                {% endfor %}
                <small>
                    {% if is_paginated %}
                    <hr>
                        <nav aria-label="Page navigation example">
                            <ul id="pagination" class="pagination justify-content-center pagination-sm">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{parameters}}" tabindex="-1">Previous</a>
                                    </li>

                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                                    </li>
                                {% endif %}
                                {% for object in page_obj.paginator.page_range %}
                                    <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}&{{parameters}}">{{ forloop.counter }}</a></li>
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{parameters}}">Next</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#">Next</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                </small>
            </div>
        </div>
    </main>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/news/news.js' %}"></script>
{% endblock %}

templates/news/polls.html
{% extends "layout/base.html" %}
{% load static %}
{% load timeConverter %}
{% block title %}
    Jobs - News Crawler
{% endblock %}
{% block custom_static %}
    {% endblock %}
{% block navbar %}
{% endblock %}

{% block content %}
    <main class="container">
        <div class="align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
            <form action="" method="get">
                <div class="row">
                    <div class="col-sm-10">
                        <input type="text" value="{{search}}" name="search" class="form-control search_bar" placeholder="search text">
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-primary btn-block">Search</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <h6 class="border-bottom pb-2 mb-0">
                {% block page_title %}
                    Polls updates
                {% endblock %}
            </h6>
            <div id="replaceable_content" data-filter-url="{% url 'news:news_poll_home' %}">
                {% for item in page_obj %}
                    <div class="d-flex text-muted pt-3">
                        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>

                        <p class="pb-3 mb-0 small lh-sm border-bottom">
                            <strong class="d-block text-gray-dark">Posted by: @{{item.by}} | added: {{item.time|time_converter}}</strong>
                            <a href="{% url 'news:news_item_detail' item.pk %}">
                                {{item.title}}
                            </a>
                            <br>
                            <br>
                            Synchronised {{item.added|timesince}} ago.
                        </p>
                    </div>
                {% endfor %}
                <small>
                    {% if is_paginated %}
                        <hr>
                            <nav aria-label="Page navigation example">
                                <ul class="pagination justify-content-center pagination-sm">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{parameters}}" tabindex="-1">Previous</a>
                                        </li>

                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link" href="#" tabindex="-1">Previous</a>
                                        </li>
                                    {% endif %}
                                    {% for object in page_obj.paginator.page_range %}
                                        <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}&{{parameters}}">{{ forloop.counter }}</a></li>
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{parameters}}">Next</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link" href="#">Next</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                    {% endif %}
                </small>
            </div>
        </div>
    </main>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/news/news.js' %}"></script>
{% endblock %}

templates/news/story.html
{% extends "layout/base.html" %}
{% load static %}
{% load timeConverter %}
{% block title %}
    Jobs - News Crawler
{% endblock %}
{% block custom_static %}
    {% endblock %}
{% block navbar %}
{% endblock %}

{% block content %}
    <main class="container">
        <div class="align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
            <form action="" method="get">
                <div class="row">
                    <div class="col-sm-10">
                        <input type="text" value="{{search}}" name="search" class="form-control search_bar" placeholder="search text">
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-primary btn-block">Search</button>
                    </div>
                </div>
            </form>
      </div>

      <div class="my-3 p-3 bg-body rounded shadow-sm">
          <h6 class="border-bottom pb-2 mb-0">
              {% block page_title %}
                Story updates
              {% endblock %}
          </h6>
          <div id="replaceable_content" data-filter-url="{% url 'news:news_story_home' %}">
              {% for item in page_obj %}
                  <div class="d-flex text-muted pt-3">
                      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
                      <p class="pb-3 mb-0 small lh-sm border-bottom">
                          <strong class="d-block text-gray-dark">Posted by: @{{item.by}} | added: {{item.time|time_converter}}</strong>
                            <a href="{% url 'news:news_item_detail' item.pk %}">
                                {{item.title}}
                            </a>
                            <br>
                            <br>
                            Synchronised {{item.added|timesince}} ago.
                      </p>
                  </div>
              {% endfor %}
              <small>
                  {% if is_paginated %}
                    <hr>
                        <nav aria-label="Page navigation example">
                            <ul id="pagination" class="pagination justify-content-center pagination-sm">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{parameters}}" tabindex="-1">Previous</a>
                                    </li>

                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                                    </li>
                                {% endif %}
                                {% for object in page_obj.paginator.page_range %}
                                    <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}&{{parameters}}">{{ forloop.counter }}</a></li>
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{parameters}}">Next</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#">Next</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                  {% endif %}
              </small>
          </div>
      </div>
    </main>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/news/news.js' %}"></script>
{% endblock %}