config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="News Crawler API",
      default_version='v1',
      description="This project provide API endpoints for Nes Crawling",
      #terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="omolojakazeem@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    #path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico')))

]

news/urls.py
from django.urls import path
from rest_framework import routers

from .apis import NewsList, NewsRetrieveUpdateDelete
from .views import NewsHomeView, JobsHomeView, StoryHomeView, PollHomeView, ItemDetailView

app_name = 'news'

apipatterns = [
    path('api/', NewsList.as_view(), name='news'),
    path('api/detail/<int:id>', NewsRetrieveUpdateDelete.as_view(), name='news_detail'),
]

urlpatterns = [
    path('', NewsHomeView.as_view(), name='news_home'),
    path('jobs/', JobsHomeView.as_view(), name='news_job_home'),
    path('stories/', StoryHomeView.as_view(), name='news_story_home'),
    path('polls/', PollHomeView.as_view(), name='news_poll_home'),
    path('detail/<int:pk>', ItemDetailView.as_view(), name='news_item_detail'),
]+apipatterns

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="{% static 'js/jquery/jquery3.6.1.js' %}"></script>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block custom_static %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'news:news_home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'news:news_job_home' %}">Jobs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'news:news_story_home' %}">Stories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'news:news_poll_home' %}">Poll</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% block content %}

{% endblock %}

{% block custom_js %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

</body>
</html>